 ---
- hosts: localhost
  gather_facts: no
  become: no

  vars:
    image_name: "seeshellol/python-app"
    image_tag: "v0.2"
    listen_port: "5003"

  tasks:
    - name: Load credentials  Ansible Vault
      ansible.builtin.include_vars:
        file: my-dockerhub-cred.yml

    - name: Login to Docker Hub
      community.general.docker_login:
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_password }}"
       build:
          path: ./
        name: "{{ image_name }}"
        repository: "{{ image_name }}"
        tag: "{{ image_tag }}"
        push: true
        source: build

    - name: Run a container
      docker_container:
        name: python-app-container
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        auto_remove: yes
        ports:
         - "{{ listen_port }}:{{ listen_port }}"
        env:
          PORT: "{{ listen_port }}"
        healthcheck:
          test: ["CMD", "curl", "--fail", "http://localhost:5003"]
          interval: 10s
          retries: 3
          start_period: 5s
                               