name: ci

on:
  push:
    branches:
      - "docker_compose"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Compose
        run: docker-compose -f docker-compose.yml build
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push
        run: docker-compose -f seeshellol/my-comopse-nginx/docker-compose.yml push
