
name: CI Feature branch

on:
  push:
    branches:
      - "M1-4-2-CI-Practice"

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
  lint-and-style:
    name: Code Lint and Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install black
          pip install pylint
          pip install types-Flask mypy
      - name: Check code style with black
        run: black --diff --check $(git ls-files '*.py')
      - name: Run pylint
        run: pylint --disable=all --enable=unused-import $(git ls-files '*.py')
      - name: Lint with Markdown-lint
        uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.json
          files: '**/*.md'
          ignore: node_modules
          version: 0.28.1
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v2
      
    - name : Install Packages 
      run : pip install pytest
      
    - name : Run tests 
      working-directory: ./app
      run : python -m unittest app_test.py
      
      
